# Generated by Django 4.2.13 on 2024-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonsrun',
            name='output_directory',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
