# Generated by Django 4.2.13 on 2024-09-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baserecipe',
            name='is_default',
        ),
        migrations.AddField(
            model_name='dragonsrecipe',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
