# Generated by Django 4.2.13 on 2024-05-31 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRAGONSReduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='starting', max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='goats_tom.dragonsrecipe')),
            ],
        ),
    ]
