# Generated by Django 4.2.16 on 2025-01-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0012_alter_reduceddatum_data_product_and_more'),
        ('goats_tom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProductMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('dataproduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='tom_dataproducts.dataproduct')),
            ],
        ),
    ]
