# Generated by Django 4.2.13 on 2024-09-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0002_remove_baserecipe_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dragonsfile',
            name='enabled',
        ),
    ]
